- type: job
  id: Chaplain
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: JobChaplain
  startingGear: ChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-hd # imp
  access:
  - Service #imp edit
  - Chapel
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles and transform null rods.

- type: startingGear
  id: ChaplainGear
  equipment:
    id: ChaplainPDA
    ears: ClothingHeadsetService
  storage:
    back:
#    - Bible #imp now handled by loadouts
    - RubberStampChaplain
    - NullRodDefault # imp
